name: Build OWP Master NGIAB Image

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

env:
  OWP_IMAGE_VERSION: "0.1.0"

permissions:
  contents: read

concurrency:
  group: owp-master-image-build
  cancel-in-progress: false

jobs:
  build-and-push-owp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout owp-master
        uses: actions/checkout@v4.2.2
        with:
          ref: owp-master

      - name: Build and Push OWP Master Image
        uses: ./.github/actions/docker-build
        with:
          dockerfile-tag: owp-master
          docker-tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ciroh-ngen-image:owp-master
            ${{ secrets.DOCKERHUB_USERNAME }}/ciroh-ngen-image:owp-${{ env.OWP_IMAGE_VERSION }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          buildcloud-endpoint: ${{ secrets.BUILDCLOUD_ENDPOINT }}